version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  backend:
    build: 
      context: ./repo/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
      - DEV_DATABASE_URL=postgresql://user:password@db:5432/mydatabase
      - TEST_DATABASE_URL=postgresql://user:password@db:5432/mydatabase
      - PROD_DATABASE_URL=postgresql://user:password@db:5432/mydatabase
      - JWT_SECRET=your_super_secret_jwt_key
      - SECRET_KEY=your_super_secret_jwt_key
      - APP_ENV=dev
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  # React Frontend
  frontend:
    build:
      context: ./repo/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

# Named volume for database persistence
volumes:
  postgres_data: 