"""Create users table

Revision ID: 310289b79e4b
Revises: 5fc9f7387e40
Create Date: 2025-06-22 17:53:51.098902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '310289b79e4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS dev")
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema="dev"
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True, schema="dev")
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False, schema="dev")
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True, schema="dev")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users', schema="dev")
    op.drop_index(op.f('ix_users_id'), table_name='users', schema="dev")
    op.drop_index(op.f('ix_users_email'), table_name='users', schema="dev")
    op.drop_table('users', schema="dev")
    # ### end Alembic commands ###
